version: '3.8'

services:
  app:
    image: fireflyiii/core:latest
    container_name: firefly_iii_app
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - firefly_iii_network

  db:
    image: mariadb:10.5
    container_name: firefly_iii_db
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly_iii_db:/var/lib/mysql
    networks:
      - firefly_iii_network

volumes:
  firefly_iii_upload:
  firefly_iii_db:

networks:
  firefly_iii_network:
